   function country_code(){
       return` 
       <option data-countrycode="US" value="1">US (+1)</option>
       <option data-countrycode="GB" value="44">GB (+44)</option>
       <option data-countrycode="DZ" value="213">DZ (+213)</option>
       <option data-countrycode="AD" value="376">AD (+376)</option>
       <option data-countrycode="AO" value="244">AO (+244)</option>
       <option data-countrycode="AI" value="1264">AI (+1264)</option>
       <option data-countrycode="AG" value="1268">AG (+1268)</option>
       <option data-countrycode="AR" value="54">AR (+54)</option>
       <option data-countrycode="AM" value="374">AM (+374)</option>
       <option data-countrycode="AW" value="297">AW (+297)</option>
       <option data-countrycode="AU" value="61">AU (+61)</option>
       <option data-countrycode="AT" value="43">AT (+43)</option>
       <option data-countrycode="AZ" value="994">AZ (+994)</option>
       <option data-countrycode="BS" value="1242">BS (+1242)</option>
       <option data-countrycode="BH" value="973">BH (+973)</option>
       <option data-countrycode="BD" value="880">BD (+880)</option>
       <option data-countrycode="BB" value="1246">BB (+1246)</option>
       <option data-countrycode="BY" value="375">BY (+375)</option>
       <option data-countrycode="BE" value="32">BE (+32)</option>
       <option data-countrycode="BZ" value="501">BZ (+501)</option>
       <option data-countrycode="BJ" value="229">BJ (+229)</option>
       <option data-countrycode="BM" value="1441">BM (+1441)</option>
       <option data-countrycode="BT" value="975">BT (+975)</option>
       <option data-countrycode="BO" value="591">BO (+591)</option>
       <option data-countrycode="BA" value="387">BA (+387)</option>
       <option data-countrycode="BW" value="267">BW (+267)</option>
       <option data-countrycode="BR" value="55">BR (+55)</option>
       <option data-countrycode="BN" value="673">BN (+673)</option>
       <option data-countrycode="BG" value="359">BG (+359)</option>
       <option data-countrycode="BF" value="226">BF (+226)</option>
       <option data-countrycode="BI" value="257">BI (+257)</option>
       <option data-countrycode="KH" value="855">KH (+855)</option>
       <option data-countrycode="CM" value="237">CM (+237)</option>
       <option data-countrycode="CA" value="1">CA (+1)</option>
       <option data-countrycode="CV" value="238">CV (+238)</option>
       <option data-countrycode="KY" value="1345">KY (+1345)</option><option data-countrycode="CF" value="236">CF (+236)</option><option data-countrycode="CL" value="56">CL (+56)</option>
       <option data-countrycode="CN" value="86">CN (+86)</option>
       <option data-countrycode="CO" value="57">CO (+57)</option>
       <option data-countrycode="KM" value="269">KM (+269)</option>
       <option data-countrycode="CG" value="242">CG (+242)</option>
       <option data-countrycode="CK" value="682">CK (+682)</option>
       <option data-countrycode="CR" value="506">CR (+506)</option>
       <option data-countrycode="HR" value="385">HR (+385)</option>
       <option data-countrycode="CY" value="90">CY - N (+90)</option>
       <option data-countrycode="CY" value="357">CY - S (+357)</option>
       <option data-countrycode="CZ" value="420">CZ (+420)</option>
       <option data-countrycode="DK" value="45">DK (+45)</option>
       <option data-countrycode="DJ" value="253">DJ (+253)</option>
       <option data-countrycode="DM" value="1809">DM (+1809)</option>
       <option data-countrycode="DO" value="1809">DO (+1809)</option>
       <option data-countrycode="EC" value="593">EC (+593)</option>
       <option data-countrycode="EG" value="20">EG (+20)</option>
       <option data-countrycode="SV" value="503">SV (+503)</option>
       <option data-countrycode="GQ" value="240">GQ (+240)</option>
       <option data-countrycode="ER" value="291">ER (+291)</option>
       <option data-countrycode="EE" value="372">EE (+372)</option>
       <option data-countrycode="ET" value="251">ET (+251)</option>
       <option data-countrycode="FK" value="500">FK (+500)</option>
       <option data-countrycode="FO" value="298">FO (+298)</option>
       <option data-countrycode="FJ" value="679">FJ (+679)</option>
       <option data-countrycode="FI" value="358">FI (+358)</option>
       <option data-countrycode="FR" value="33">FR (+33)</option>
       <option data-countrycode="GF" value="594">GF (+594)</option>
       <option data-countrycode="PF" value="689">PF (+689)</option>
       <option data-countrycode="GA" value="241">GA (+241)</option>
       <option data-countrycode="GM" value="220">GM (+220)</option>
       <option data-countrycode="GE" value="7880">GE (+7880)</option>
       <option data-countrycode="DE" value="49">DE (+49)</option>
       <option data-countrycode="GH" value="233">GH (+233)</option>
       <option data-countrycode="GI" value="350">GI (+350)</option>
       <option data-countrycode="GR" value="30">GR (+30)</option>
       <option data-countrycode="GL" value="299">GL (+299)</option>
       <option data-countrycode="GD" value="1473">GD (+1473)</option>
       <option data-countrycode="GP" value="590">GP (+590)</option>
       <option data-countrycode="GU" value="671">GU (+671)</option>
       <option data-countrycode="GT" value="502">GT (+502)</option>
       <option data-countrycode="GN" value="224">GN (+224)</option>
       <option data-countrycode="GW" value="245">GW (+245)</option>
       <option data-countrycode="GY" value="592">GY (+592)</option>
       <option data-countrycode="HT" value="509">HT (+509)</option>
       <option data-countrycode="HN" value="504">HN (+504)</option>
       <option data-countrycode="HK" value="852">HK (+852)</option>
       <option data-countrycode="HU" value="36">HU (+36)</option>
       <option data-countrycode="IS" value="354">IS (+354)</option>
       <option data-countrycode="IN" value="91">IN (+91)</option>
       <option data-countrycode="MU" value="230">MU (+230)</option>
       <option data-countrycode="ID" value="62">ID (+62)</option>
       <option data-countrycode="IQ" value="964">IQ (+964)</option>
       <option data-countrycode="IR" value="98">IR (+98)</option>
       <option data-countrycode="IE" value="353">IE (+353)</option>
       <option data-countrycode="IL" value="972">IL (+972)</option>
       <option data-countrycode="IT" value="39">IT (+39)</option>
       <option data-countrycode="JM" value="1876">JM (+1876)</option>
       <option data-countrycode="JP" value="81">JP (+81)</option>
       <option data-countrycode="JO" value="962">JO (+962)</option>
       <option data-countrycode="KZ" value="7">KZ (+7)</option>
       <option data-countrycode="KE" value="254">KE (+254)</option>
       <option data-countrycode="KI" value="686">KI (+686)</option>
       <option data-countrycode="KP" value="850">KP (+850)</option>`
   }
   export default country_code;